services:
  - type: web
    name: tapcheck-api
    env: python
    plan: free
    buildCommand: python --version && pip install --upgrade pip==22.3.1 && pip install setuptools==65.5.0 wheel==0.38.4 && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16 